# Site settings
title: Braver Measures Consulting
email: braver@ik.me
url: https://bravermeasuresconsulting.com
description: "Research, strategy, and project leadership for values-driven organizations tackling complex problems"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#4fe4f5'

# Footer settings
footer: Braver Measures Consulting

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://linkedin.com/in/sbouchat
  - title: instagram
    url: https://www.instagram.com/bravermeasures
  - title: ghost
    url: https://evidenceandevil.com

# Build settings
markdown: kramdown
permalink: pretty


